### ISSUE TITLE
Update to VS 2022

### ISSUE THREAD

**Issue by ClassyCircuit** [HumanGamer/TODOHighlighter#7]
When are you going to update this extension for Visual Studio 2022 ?

**Comment by VAllens** [comment]
I created the PR: https://github.com/HumanGamer/TODOHighlighter/pull/8
Added support for `Visual Studio 2022`.
Let's follow it together. 

If you can't wait, you can use my build package: [TODOHighlighter.VS2022.vsix.zip](https://github.com/HumanGamer/TODOHighlighter/files/8228855/TODOHighlighter.VS2022.vsix.zip) :)
@janissimsons

**Comment by HumanGamer** [comment]
the PR was merged.

**Comment by ClassyCircuit** [comment]
@HumanGamer I don't see it available on the extension store. It shows up only for VS 2019.
Where can I download it?

**Comment by HumanGamer** [comment]
I haven't gotten around to updating the store page yet, I've been quite busy. For now you will have to compile it yourself or try the one VAllens sent.

**Comment by ClassyCircuit** [comment]
Ok, thanks, I compiled it myself and it's working.
If anyone else needs it, here is the latest compiled version:

[TODOHighlighter.zip](https://github.com/HumanGamer/TODOHighlighter/files/9253969/TODOHighlighter.zip)

**Comment by VAllens** [comment]
> Ok, thanks, I compiled it myself and it's working. If anyone else needs it, here is the latest compiled version:
> 
> [TODOHighlighter.zip](https://github.com/HumanGamer/TODOHighlighter/files/9253969/TODOHighlighter.zip)

Please see here: https://github.com/HumanGamer/TODOHighlighter/issues/7#issuecomment-1067868581

@janissimsons
